<?php

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5bc26122a92ad',
		'title' => '[Page] Overrides',
		'fields' => array(
			array(
				'key' => 'field_5bc318c304751',
				'label' => 'Navigation',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5bc26126286c2',
				'label' => 'Custom Navigation',
				'name' => 'page_custom_navigation',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5bc33c5551a6c',
				'label' => 'Navigation Show',
				'name' => 'navigation_show',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bc26126286c2',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'show' => 'Show',
					'hide' => 'Hide',
				),
				'default_value' => array(
				),
				'allow_null' => 1,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_5bc3406c8a592',
				'label' => 'Navigation Type',
				'name' => 'navigation_type',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bc26126286c2',
							'operator' => '==',
							'value' => '1',
						),
						array(
							'field' => 'field_5bc33c5551a6c',
							'operator' => '==',
							'value' => 'show',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'default' => 'Default',
					'fullscreen' => 'Fullscreen',
					'slide' => 'Slide',
					'aside' => 'Aside',
				),
				'default_value' => array(
				),
				'allow_null' => 1,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_5bc3a717dfaa9',
				'label' => 'Navigation Opaque',
				'name' => 'navigation_opaque',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bc26126286c2',
							'operator' => '==',
							'value' => '1',
						),
						array(
							'field' => 'field_5bc33c5551a6c',
							'operator' => '==',
							'value' => 'show',
						),
						array(
							'field' => 'field_5bc3406c8a592',
							'operator' => '!=',
							'value' => 'aside',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'enable' => 'Enable',
					'disable' => 'Disable',
				),
				'default_value' => array(
				),
				'allow_null' => 1,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_5bc3a769dfaac',
				'label' => 'Transparent',
				'name' => 'navigation_transparent',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bc26126286c2',
							'operator' => '==',
							'value' => '1',
						),
						array(
							'field' => 'field_5bc33c5551a6c',
							'operator' => '==',
							'value' => 'show',
						),
						array(
							'field' => 'field_5bc3406c8a592',
							'operator' => '!=',
							'value' => 'aside',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'enable' => 'Enable',
					'disable' => 'Disable',
				),
				'default_value' => array(
				),
				'allow_null' => 1,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_5bc3a788dfaad',
				'label' => 'Transparent Always',
				'name' => 'navigation_transparent_always',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bc26126286c2',
							'operator' => '==',
							'value' => '1',
						),
						array(
							'field' => 'field_5bc33c5551a6c',
							'operator' => '==',
							'value' => 'show',
						),
						array(
							'field' => 'field_5bc3406c8a592',
							'operator' => '!=',
							'value' => 'aside',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'enable' => 'Enable',
					'disable' => 'Disable',
				),
				'default_value' => array(
				),
				'allow_null' => 1,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_5bc3a7a1dfaae',
				'label' => 'Sticky',
				'name' => 'navigation_sticky',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bc26126286c2',
							'operator' => '==',
							'value' => '1',
						),
						array(
							'field' => 'field_5bc33c5551a6c',
							'operator' => '==',
							'value' => 'show',
						),
						array(
							'field' => 'field_5bc3406c8a592',
							'operator' => '!=',
							'value' => 'aside',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'enable' => 'Enable',
					'disable' => 'Disable',
				),
				'default_value' => array(
				),
				'allow_null' => 1,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_5bc3a7b4dfaaf',
				'label' => 'Hide on Scroll',
				'name' => 'navigation_hide_on_scroll',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bc26126286c2',
							'operator' => '==',
							'value' => '1',
						),
						array(
							'field' => 'field_5bc33c5551a6c',
							'operator' => '==',
							'value' => 'show',
						),
						array(
							'field' => 'field_5bc3406c8a592',
							'operator' => '!=',
							'value' => 'aside',
						),
						array(
							'field' => 'field_5bc3a7a1dfaae',
							'operator' => '==',
							'value' => 'enable',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'enable' => 'Enable',
					'disable' => 'Disable',
				),
				'default_value' => array(
				),
				'allow_null' => 1,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_5bc3a7cbdfab1',
				'label' => 'White Text on Top',
				'name' => 'navigation_white_text_on_top',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bc26126286c2',
							'operator' => '==',
							'value' => '1',
						),
						array(
							'field' => 'field_5bc33c5551a6c',
							'operator' => '==',
							'value' => 'show',
						),
						array(
							'field' => 'field_5bc3406c8a592',
							'operator' => '!=',
							'value' => 'aside',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'enable' => 'Enable',
					'disable' => 'Disable',
				),
				'default_value' => array(
				),
				'allow_null' => 1,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_5bc31a3995664',
				'label' => 'Footer',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5bc31a7895666',
				'label' => 'Custom Footer',
				'name' => 'page_custom_footer',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5bc31aef95668',
				'label' => 'Footer Show',
				'name' => 'footer_show',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bc31a7895666',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'show' => 'Show',
					'hide' => 'Hide',
				),
				'default_value' => array(
				),
				'allow_null' => 1,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_5bc31a5595665',
				'label' => 'Footer Layout',
				'name' => 'footer_layout',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bc31a7895666',
							'operator' => '==',
							'value' => '1',
						),
						array(
							'field' => 'field_5bc31aef95668',
							'operator' => '==',
							'value' => 'show',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'style-1' => 'Style 1',
					'style-2' => 'Style 2',
					'style-3' => 'Style 3',
					'style-4' => 'Style 4',
					'style-5' => 'Style 5',
					'style-6' => 'Style 6',
					'widgetized' => 'Widgetized',
					'shortcode' => 'Shortcode',
				),
				'default_value' => array(
				),
				'allow_null' => 1,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_5be6a77d19ddc',
				'label' => 'Footer Shortcode',
				'name' => 'footer_shortcode',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bc31a7895666',
							'operator' => '==',
							'value' => '1',
						),
						array(
							'field' => 'field_5bc31aef95668',
							'operator' => '==',
							'value' => 'show',
						),
						array(
							'field' => 'field_5bc31a5595665',
							'operator' => '==',
							'value' => 'shortcode',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 4,
				'new_lines' => '',
			),
			array(
				'key' => 'field_5bc31ab095667',
				'label' => 'Footer Fixed',
				'name' => 'footer_fixed',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bc31a7895666',
							'operator' => '==',
							'value' => '1',
						),
						array(
							'field' => 'field_5bc31aef95668',
							'operator' => '==',
							'value' => 'show',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'enable' => 'Enable',
					'disable' => 'Disable',
				),
				'default_value' => array(
				),
				'allow_null' => 1,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_5bc3271441b79',
				'label' => 'Back to Top',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5bc3274541b7a',
				'label' => 'Custom Back to Top',
				'name' => 'page_custom_back_to_top',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5bc326e541b78',
				'label' => 'Back to Top',
				'name' => 'back_to_top',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bc3274541b7a',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'show' => 'Show',
					'hide' => 'Hide',
				),
				'default_value' => array(
				),
				'allow_null' => 1,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_5bcce41216338',
				'label' => 'Onepage Navigation',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5bcce42716339',
				'label' => 'Onepage Navigation',
				'name' => 'onepage_navigation',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5bcce43f1633a',
				'label' => 'Navigation Name',
				'name' => 'onepage_navigation_name',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bcce42716339',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5bcf4fc2afa51',
				'label' => 'Site Protection',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5bcf4fd2afa52',
				'label' => 'Custom Site Protection',
				'name' => 'page_custom_site_protection',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5bcf4ff1afa53',
				'label' => 'Site Protection',
				'name' => 'site_protection',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5bcf4fd2afa52',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'show' => 'Show',
					'hide' => 'Hide',
				),
				'default_value' => array(
				),
				'allow_null' => 1,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'portfolio',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5b7bcee3b72ff',
		'title' => '[Post Format] Gallery',
		'fields' => array(
			array(
				'key' => 'field_5b7bceedbd4fb',
				'label' => 'Gallery Images',
				'name' => 'post_gallery_images',
				'type' => 'gallery',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'min' => '',
				'max' => '',
				'insert' => 'append',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'gallery',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
		'modified' => 1534852873,
	));

	acf_add_local_field_group(array(
		'key' => 'group_5b7bcebd66024',
		'title' => '[Post Format] Video',
		'fields' => array(
			array(
				'key' => 'field_5b7bcec5cbf87',
				'label' => 'Video URL',
				'name' => 'post_video_url',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'video',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
		'modified' => 1534852889,
	));

	acf_add_local_field_group(array(
		'key' => 'group_5bab4215775a6',
		'title' => '[Post] Single Post',
		'fields' => array(
			array(
				'key' => 'field_5bab421cfb5ab',
				'label' => 'Post Shortcode',
				'name' => 'single_post_shortcode',
				'type' => 'textarea',
				'instructions' => 'For example [test option="style-1"]',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 4,
				'new_lines' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
		'modified' => 1537950677,
	));

	acf_add_local_field_group(array(
		'key' => 'group_59be493b08ac2',
		'title' => '[Widget] Banner',
		'fields' => array(
			array(
				'key' => 'field_59be493b0bcd9',
				'label' => 'Banner Image',
				'name' => 'banner_image',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'id',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_59be493b0bce7',
				'label' => 'Link',
				'name' => 'banner_link',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_59db8a4804692',
				'label' => 'Target',
				'name' => 'banner_target',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'_self' => 'Self',
					'_blank' => 'Blank',
				),
				'default_value' => array(
					0 => '_self',
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'widget',
					'operator' => '==',
					'value' => 'vlthemes_widget_banner',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
		'modified' => 1526056480,
	));

	acf_add_local_field_group(array(
		'key' => 'group_5a23f044c6765',
		'title' => '[Widget] Instagram',
		'fields' => array(
			array(
				'key' => 'field_5a23f06736633',
				'label' => 'Username',
				'name' => 'instagram_username',
				'type' => 'text',
				'instructions' => '@username or #tag',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5a23f07836634',
				'label' => 'Max Photos',
				'name' => 'instagram_max_photos',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 8,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5a23f0af36635',
				'label' => 'Size',
				'name' => 'instagram_photo_size',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'thumbnail' => 'Thumbnail',
					'small' => 'Small',
					'large' => 'Large',
					'original' => 'Original',
				),
				'default_value' => array(
					0 => 'thumbnail',
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'widget',
					'operator' => '==',
					'value' => 'vlthemes_widget_instagram',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
		'modified' => 1535459085,
	));

	acf_add_local_field_group(array(
		'key' => 'group_59be47f52a277',
		'title' => '[Widget] Popular Posts',
		'fields' => array(
			array(
				'key' => 'field_59be47f52d5c0',
				'label' => 'Number of Posts',
				'name' => 'popular_posts_number_of_posts',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 3,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 1,
				'max' => '',
				'step' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'widget',
					'operator' => '==',
					'value' => 'vlthemes_widget_popular_posts',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
		'modified' => 1526056480,
	));

	acf_add_local_field_group(array(
		'key' => 'group_59be4075bbab4',
		'title' => '[Widget] Recent Posts',
		'fields' => array(
			array(
				'key' => 'field_59be408062a67',
				'label' => 'Number of Posts',
				'name' => 'recent_posts_number_of_posts',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 3,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 1,
				'max' => '',
				'step' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'widget',
					'operator' => '==',
					'value' => 'vlthemes_widget_recent_posts',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
		'modified' => 1526056480,
	));

	acf_add_local_field_group(array(
		'key' => 'group_58cb9676d6b14',
		'title' => '[Widget] Socials',
		'fields' => array(
			array(
				'key' => 'field_5b852fedf04ce',
				'label' => 'Style',
				'name' => 'social_style',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'style-1' => 'Style 1',
					'style-2' => 'Style 2',
					'style-3' => 'Style 3',
					'style-4' => 'Style 4',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 'style-1',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5b852c571e93f',
				'label' => 'Social List',
				'name' => 'social_list',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => 'Add new social',
				'sub_fields' => array(
					array(
						'key' => 'field_5b852ca91e940',
						'label' => 'Social Icon',
						'name' => 'social_icon',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'fa fa-twitch' => 'Twitch',
							'fa fa-vimeo' => 'Vimeo',
							'fa fa-youtube' => 'Youtube',
							'fa fa-facebook' => 'Facebook',
							'fa fa-google-plus' => 'Google-Plus',
							'fa fa-twitter' => 'Twitter',
							'fa fa-pinterest' => 'Pinterest',
							'fa fa-instagram' => 'Instagram',
							'fa fa-linkedin' => 'LinkedIn',
							'fa fa-behance' => 'Behance',
							'fa fa-odnoklassniki' => 'Odnoklassniki',
							'fa fa-skype' => 'Skype',
							'fa fa-vk' => 'VK',
							'fa fa-steam' => 'Steam',
							'fa fa-bitbucket' => 'Bitbucket',
							'fa fa-dropbox' => 'Dropbox',
							'fa fa-dribbble' => 'Dribbble',
							'fa fa-deviantart' => 'Deviantart',
							'fa fa-flickr' => 'Flickr',
							'fa fa-foursquare' => 'Foursquare',
							'fa fa-github' => 'Github',
							'fa fa-medium' => 'Medium',
							'fa fa-paypal' => 'PayPal',
							'fa fa-reddit' => 'Reddit',
							'fa fa-soundcloud' => 'SoundCloud',
							'fa fa-slack' => 'Slack',
							'fa fa-tumblr' => 'Tumblr',
							'fa fa-wordpress' => 'WordPress',
						),
						'default_value' => array(
						),
						'allow_null' => 1,
						'multiple' => 0,
						'ui' => 0,
						'ajax' => 0,
						'return_format' => 'value',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b852d2c1e941',
						'label' => 'Social Url',
						'name' => 'social_url',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'widget',
					'operator' => '==',
					'value' => 'vlthemes_widget_socials',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
		'modified' => 1537782620,
	));

	acf_add_local_field_group(array(
		'key' => 'group_58cb932f7bbbf',
		'title' => '[Widget] Subscribe',
		'fields' => array(
			array(
				'key' => 'field_58cb933701631',
				'label' => 'Subscribe Text',
				'name' => 'subscribe_text',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
			array(
				'key' => 'field_58cb934801632',
				'label' => 'Subscribe URL',
				'name' => 'subscribe_url',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'widget',
					'operator' => '==',
					'value' => 'vlthemes_widget_subscribe',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
		'modified' => 1526056480,
	));

	acf_add_local_field_group(array(
		'key' => 'group_5a04b3395086a',
		'title' => '[Widget] Trending Posts',
		'fields' => array(
			array(
				'key' => 'field_5a04b33955940',
				'label' => 'Number of Posts',
				'name' => 'treinding_posts_number_of_posts',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 3,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 1,
				'max' => '',
				'step' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'widget',
					'operator' => '==',
					'value' => 'vlthemes_widget_trending_posts',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
		'modified' => 1526056480,
	));

	acf_add_local_field_group(array(
		'key' => 'group_5bfbbdd618ba5',
		'title' => '[Page] Additional',
		'fields' => array(
			array(
				'key' => 'field_5bfbbded86a97',
				'label' => 'Page Shortcode',
				'name' => 'page_shortcode',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
			),
		),
		'menu_order' => 1,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
		'modified' => 1543237375,
	));

	endif;